data:
  source: data/source
  texts: data/texts
  cleaned_texts: data/cleaned_texts
  chunks: data/chunks/prefettura_v1.2_chunks
  embeddings: data/embeddings/prefettura_v1.2_embeddings
  destination: data/results
supported_formats:
  - .text
  - .txt
  - .jpg
  - .jpeg
  - .gif
  - .png
  - .pdf
embedding_model: intfloat/multilingual-e5-large
embedding_dim: 1024
collection_name: gotmat_collection
milvus_host: localhost
milvus_port: 19530
model_path: Helsinki-NLP/opus-mt-it-en
adapter_path: models/fine_tuned_models/opus-mt-it-en-v1/model
tokenizer_path: models/fine_tuned_models/opus-mt-it-en-v1/tokenizer
max_length: 512
max_new_tokens: 200
device: auto
max_chunk_words: 500
min_chunk_length: 10
max_contexts: 5
max_context_length: 1000
tessdata_dir: C:/Program Files/Tesseract-OCR/tessdata